[SR-13300] FileManager _updateTimes (microseconds)
apple/swift-corelibs-foundation pull request #2904
Opened 2020-10-17 16:40 UTC by benrimmington

The `_updateTimes` function is multiplying by `1.0e9` as if for nanoseconds, but it should be using `1.0e6` for microseconds.

The `timeval.tv_usec` value will be too large, hence the `EINVAL` errno on Raspberry Pi OS (SR-13300).

2020-10-17 19:01 UTC, MaxDesiatov reviewed
Please add tests to cover this behaviour.

2020-10-18 08:28 UTC, benrimmington commented
@MaxDesiatov I've added tests for macOS only ([1][], [2][]).

[1]: <https://github.com/apple/swift-corelibs-foundation/blob/9ebb4442a45223b252ab714a2c101748a969e2da/Sources/Foundation/FileManager.swift#L406>
[2]: <https://github.com/apple/swift-corelibs-foundation/blob/9ebb4442a45223b252ab714a2c101748a969e2da/Tests/Foundation/Tests/TestURL.swift#L728>

2020-10-18 08:31 UTC, MaxDesiatov commented
What prevents adding tests on Linux, as the bug reported on Jira is reproducible on Linux?

2020-10-18 08:38 UTC, benrimmington commented
> What prevents adding tests on Linux, as the bug reported on Jira is reproducible on Linux?

Because the test may fail on Linux, depending on the OS and filesystem:

https://github.com/apple/swift-corelibs-foundation/blob/9ebb4442a45223b252ab714a2c101748a969e2da/Tests/Foundation/Tests/TestURL.swift#L728

2020-10-18 09:37 UTC, benrimmington commented
Without this bug fix, time interval `1234567890.5` results in `timeval.tv_usec = 0.5e9`. This value is:

* rejected on Raspberry Pi OS (SR-13300);
* accepted on macOS, but the modification date is 500 seconds later than expected.

2020-10-18 09:51 UTC, MaxDesiatov commented
Sorry, I'm not sure I completely follow. Is this not supposed to fix the bug on Raspberry too? Or will that part come as a separate PR?

2020-10-18 10:18 UTC, benrimmington commented
This pull request should fix the reported bug on Raspberry Pi OS.

It will also fix an unreported bug on other POSIX platforms (e.g. where 0.5 seconds unexpectedly becomes 500 seconds).

I've updated the test for Linux, to assert that the modification date is almost equal, within an accuracy of 1 second.

2020-10-18 10:38 UTC, MaxDesiatov commented on Tests/Foundation/Tests/TestFileManager.swift
> +            try fm.setAttributes([.modificationDate: NSDate(timeIntervalSince1970: 1234567890.5)], ofItemAtPath: path)
Nitpick: could you move `1234567890.5` value to a `let` binding to reuse it in `XCTAssertEqual` below?

2020-10-18 10:59 UTC, MaxDesiatov commented
@swift-ci please test

2020-10-18 14:11 UTC, benrimmington commented
@MaxDesiatov Thanks for your help.

2020-10-18 14:49 UTC, MaxDesiatov approved these changes
Awesome, thanks!

2020-10-18 16:00 UTC, compnerd requested changes
Why are the tests marked as not windows?  The file modification time information is available on windows as well IIRC.

Can you create an extension to convert the time rather than having the two sites which use the wrong constant?  That would ensure that they don't ever drift and cases like this are localized.

2020-10-18 16:21 UTC, benrimmington commented
> Why are the tests marked as not windows? The file modification time information is available on windows as well IIRC.

An [`_updateTimes`][] function is available for Windows, but I think the tests would currently fail:

https://github.com/apple/swift-corelibs-foundation/blob/cfef71fe9e0df0a5d6430f6fb202896080a17956/Sources/Foundation/FileManager.swift#L403-L408

[`_updateTimes`]: <https://github.com/apple/swift-corelibs-foundation/blob/cfef71fe9e0df0a5d6430f6fb202896080a17956/Sources/Foundation/FileManager%2BWin32.swift#L885-L909>

2020-10-19 16:18 UTC, benrimmington commented
@compnerd I've applied your suggestions as separate commits.

2020-10-19 21:25 UTC, compnerd commented
@benrimmington thanks!  I don't mind too much about the separation of the commits, and since the intermediate states in this case should be okay, I dont think that they really matter.  The final result of this looks much better, thank you for the additional changes!

2020-10-19 21:25 UTC, compnerd approved these changes

2020-10-19 21:25 UTC, compnerd commented
@swift-ci please test

2020-10-19 21:26 UTC, compnerd commented
Should probably run this on Windows as well to make sure that it doesn't cause a regression, I can kick off a test run once the CI here passes.

2020-10-20 01:14 UTC, benrimmington commented
There was a failure in 'lldb-shell :: SwiftREPL/RedirectInput.test' on [Linux](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/4749/).

I can see the files in my working copy, but I can't find them on [GitHub](https://github.com/apple/llvm-project/tree/apple/main/lldb/test/Shell).

* "llvm-project/lldb/test/Shell/SwiftREPL/RedirectInput.test" contains:

  ```swift
  Foo.foo()
  // CHECK: ${{R0}}: String = "A"
  ```

* "llvm-project/lldb/test/Shell/SwiftREPL/Inputs/A.swift" contains:

  ```swift
  public class Foo {
    public static func foo() -> String  {
      print("A")
      return "A"
    }
  }
  ```

* The expected REPL output is intermixed with the `print("A")` output:

  ```
  $R0: String =A
   "A"
  ```

2020-10-20 02:39 UTC, benrimmington commented
I've reported the test failure as SR-13754.

2020-10-20 05:06 UTC, millenomi commented
@swift-ci please test Linux

2020-10-20 14:25 UTC, benrimmington commented
@compnerd All checks have passed. Please test on Windows (or else commit 007b850342af9c3b64074edcd29cd8040a10afac can be reverted later).

2020-10-20 18:07 UTC, compnerd commented
Tested at https://dev.azure.com/compnerd/swift-build/_build/results?buildId=40716&view=results - windows seems happy too

2020-10-27 11:46 UTC, benrimmington commented
@millenomi Do you want me to make any changes?

2020-12-09 20:57 UTC, merged