[cmake] Fix ICU static linking
apple/swift-corelibs-foundation pull request #3133
Opened 2022-01-26 20:06 UTC by Azoy

When linking Foundation, we were only passing `-licui18nswift` as a static library, but it depends on `icuucswift` and `icudataswift`, so make sure we static link against those as well.

2022-01-26 20:10 UTC, Azoy commented
@swift-ci please build toolchain linux platform

2022-01-26 20:43 UTC, stephentyrone approved these changes

2022-01-26 20:46 UTC, Azoy commented
@swift-ci please test

2022-01-26 20:56 UTC, Azoy commented
@swift-ci please test

2022-01-26 20:56 UTC, Azoy commented
@swift-ci please build toolchain linux platform

2022-01-26 21:44 UTC, compnerd requested changes
I think that we should be handling these similar to the `icuin` case - this will break builds when used outside of the host.

2022-01-27 18:38 UTC, Azoy commented
I've updated the PR to lookup the library name like `icui18n` is doing, but it requires explicitly passing `ICU_DATA_LIBRARY` in the build-script-impl, so I've done that here: https://github.com/apple/swift/pull/41041

2022-01-27 18:53 UTC, Azoy commented
@swift-ci please smoke test

2022-01-27 23:09 UTC, compnerd approved these changes

2022-01-31 10:49 UTC, MaxDesiatov commented
@swift-ci please test

2022-01-31 22:52 UTC, millenomi approved these changes

2022-02-02 19:42 UTC, merged