The Ventura Core Foundation Merge
apple/swift-corelibs-foundation pull request #4633
Opened 2022-09-19 18:29 UTC by iCharlesHu

This PR brings the FOSS portions of Core Foundation on par with with macOS Ventura, iOS 16, watchOS 9 and tvOS 16. This includes the changes shipped during the previous releases.

Most of the changes include bug fixes and performance improvements, but some are useful to highlight:
- Updated Unicode definitions of `CFString` and `NSString`-based methods, including a new method of generating and storing this information by producing headers rather than bundling binary blobs.
- Updated `CFURLComponents` to support Internationalized Domain Names (IDNs) via Punycode encoding.
- Updates to calendrical calculation correctness.
- Improved performance in several spots throughout the framework.

Some development notes:
- `CF_CROSS_PLATFORM_EXPORT` has been renamed to `CF_EXPORT_NONOBJC_ONLY` to make its use clearer.
- Development has continued using primarily `os_*_lock_*` functions rather than `CFLock` or `CFMutex`. To avoid the codebase diverging too far and make future merges easier, this patch uses `os_unfair_lock` and similar facilities where they were previously replaced by `CFLock`. These types shim to `CFLock` implementations outside of Darwin.

2022-09-19 18:29 UTC, iCharlesHu commented
@swift-ci please test

2022-09-19 18:29 UTC, iCharlesHu commented
cc @parkera

2022-09-19 18:32 UTC, iCharlesHu commented
cc @compnerd - Similar to previous merges, can we kick off a Windows build to see if there's anything breaks?

2022-10-16 04:16 UTC, AtariDreams commented
@iCharlesHu I thought this was the source compiled at Apple for macOS?

2022-10-19 22:38 UTC, 3405691582 commented on CoreFoundation/RunLoop.subproj/CFRunLoop.c
> -#elif TARGET_OS_BSD
The changes from #3004 and #4622 need to be merged back in here.

2022-10-21 00:48 UTC, 3405691582 requested changes
I was going to add more finer grained review comments but I just did the needful anyway in #4648 -- feel free to pick those commits on this pr, since I don't know off the top of my head if I can chain prs. The comments about malloc introspection need to be addressed separately though, because it's not immediately apparent how to resolve that issue.

2024-04-30 23:03 UTC, closed without merging