Replace calls to CFStringCreateWithCString with constant CFStrings
apple/swift-corelibs-foundation pull request #4694
Opened 2023-01-20 19:48 UTC by AtariDreams

This would save performance by removing unnecessary calls to CFStringCreateWithCString

2023-01-23 17:09 UTC, AtariDreams commented
@compnerd Is this good?

2023-01-23 17:55 UTC, compnerd commented
CC: @parkera

2023-01-24 17:53 UTC, parkera requested changes
I think using constant strings here is fine. One code style fix that needs to be made first before merging.

2023-01-24 17:53 UTC, parkera commented on CoreFoundation/Base.subproj/CFPlatform.c
> +        if (processName)
Our code style is to always use `{ }` on multi-line conditionals.

2023-01-24 17:57 UTC, AtariDreams commented
@parkera Done!

2023-01-24 21:57 UTC, parkera commented
@swift-ci test

2023-01-25 14:37 UTC, AtariDreams commented
I apologize. This has been fixed. Let's try again @parkera

2023-01-25 17:41 UTC, AtariDreams commented
@compnerd Could you please run the tests again and merge

2023-01-25 17:42 UTC, compnerd commented
@swift-ci please test

2023-01-25 17:47 UTC, AtariDreams commented
macOS build seems to be broken; it isn't even starting. Huh.

2023-01-25 18:01 UTC, AtariDreams commented
@compnerd Seems like the macOS Jenkins instance is broken; it will not start the pipeline

2023-01-25 19:43 UTC, AtariDreams commented
Okay everything is fixed! @compnerd Let's try it one more time. It builds.

2023-01-25 19:50 UTC, AtariDreams commented
@swift-ci test

2023-01-26 18:32 UTC, AtariDreams commented
@parkera Can we give this one more go as well?

2023-02-27 17:35 UTC, parkera commented
@swift-ci test

2023-03-01 15:25 UTC, AtariDreams commented
@parkera Everything is fixed. Can we do this one more time?

2023-03-01 20:46 UTC, AtariDreams commented
@compnerd Could you please run the tests again and merge?

2023-03-14 19:42 UTC, AtariDreams commented
Can someone please do the please test and merge thing? @compnerd @parkera

2023-03-14 23:02 UTC, parkera commented
@swift-ci test

2023-03-15 16:31 UTC, AtariDreams commented
> @swift-ci test

It passed! Can we merge please? @parkera

2023-03-16 18:20 UTC, merged

2023-03-16 21:05 UTC, compnerd commented
This might be regressing the Windows build:
https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/2845/console